### ISSUE TITLE
-

### ISSUE THREAD

**Issue by sonereker** [soner/selfhosted#1]

**Comment by soner** [comment]
Hello Soner, I'm sorry but I have no intention to give up on this username.

**Comment by sonereker** [comment]
Hello, and sorry for bothering you again. I have an offer this time; I can give you `soner at duck.com` email forwarder (free email protection service provided by https://duckduckgo.com/email/) for `soner` username? @soner

**Comment by sonereker** [comment]
Hello, and sorry for bothering again. I offer `soner at duck dot com` email alias with email protection for this username. Service is provided by https://duckduckgo.com/email/ and it's free. What do you think? Thank you.

**Comment by sonereker** [comment]
> Hello Soner, I'm sorry but I have no intention to give up on this username.

Hello @soner again, I've emailed you about this, but not sure if you check that email. I noticed that `/pavelsilar` username is available (took it for you). I'd like to ask you if by any chance you want to exchange with `/soner`?

Thank you.
